version: "3.3"

services:
  radium:
    container_name: radium-order
    volumes:
      - ./custom-assets:/app/custom-assets\
      - ./config:/app/config
    ports:
      - "${RADIUM_PORT}:3000"
    environment:
      BASE_URL: "${BASE_URL}"
      INITIAL_SOURCE_TYPE: "${INITIAL_SOURCE_TYPE}"
      INITIAL_SOURCE_URL: "${INITIAL_SOURCE_URL}"
      ENABLE_CHAT: "${ENABLE_CHAT}"
      REQUIRE_USERNAME: "${REQUIRE_USERNAME}"
    build:
      context: .
      dockerfile: Dockerfile
